# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 17:09
from __future__ import unicode_literals

from decimal import Decimal
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fuid', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('strnumr', models.CharField(blank=True, max_length=255, null=True)),
                ('postcod', models.CharField(blank=True, max_length=7, null=True)),
                ('plaprov', models.CharField(blank=True, max_length=255, null=True)),
                ('woonopp', models.IntegerField()),
                ('percopp', models.IntegerField()),
                ('vrprijs', models.IntegerField()),
                ('sqprijs', models.FloatField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('dellink', models.CharField(blank=True, max_length=255, null=True)),
                ('rdx', models.CharField(blank=True, max_length=255, null=True)),
                ('rdy', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=9)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'house',
                'managed': True,
            },
        ),
    ]
